//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allergy
    {
        public int AllergyID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Allergy1 { get; set; }
        public string Reaction { get; set; }
        public string Severity { get; set; }
    
        public virtual Patient Patient {internal get; set; }
    }
}
