//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactsID { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> Contactid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Demographic Demographic {internal get; set; }
    }
}
