//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSender
    {
        public int DataSenderID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<int> Sender { get; set; }
        public string Text { get; set; }
        public string PictureInfo { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<bool> Send { get; set; }
    
        public virtual Doctor Doctor {internal get; set; }
        public virtual Patient Patient {internal get; set; }
    }
}
