//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSender
    {
        public int DataSenderID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> ReseiverID { get; set; }
        public string Text { get; set; }
        public string PictureInfo { get; set; }
        public byte[] Picture { get; set; }
        public string Date { get; set; }
    
        public virtual Demographic Demographic {internal get; set; }
    }
}
