//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentsID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public string Date { get; set; }
        public byte[] file { get; set; }
        public Nullable<int> Document_TypeID { get; set; }
    
        public virtual Demographic Demographic { get; set; }
        public virtual DocType DocType { get; set; }
    }
}
