//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EHRsystemEntities : DbContext
    {
        public EHRsystemEntities()
            : base("name=EHRsystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Treat_Medicines> Treat_Medicines { get; set; }
        public virtual DbSet<Communication> Communications { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Demographic> Demographics { get; set; }
        public virtual DbSet<DIagnosi> DIagnosis { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Visit> Visits { get; set; }
        public virtual DbSet<DataSender> DataSenders { get; set; }
    }
}
