//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treat_Medicines
    {
        public int TreatmentID { get; set; }
        public Nullable<int> VisitID { get; set; }
        public string ATC_CODES { get; set; }
        public string Dosage { get; set; }
    
        public virtual Visit Visit {internal get; set; }
    }
}
