//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EHRWEBAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Visit()
        {
            this.DIagnosis = new HashSet<DIagnosi>();
            this.Treat_Medicines = new HashSet<Treat_Medicines>();
        }
    
        public int VisitID { get; set; }
        public int DoctorPersonID { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int NumberOfVisit { get; set; }
        public string Date { get; set; }
    
        public virtual Demographic Demographic {internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIagnosi> DIagnosis {internal get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Treat_Medicines> Treat_Medicines {internal get; set; }
    }
}
